### PR TITLE
Use the updated ZEI API and prepare for TM

### PR DESCRIPTION
**Pull request by findora-sun**
* **make sure that you have executed all the following process and no errors occur**
  - [x] make fmt
  - [ ] make lint
  - [ ] make test

* **The major changes of this PR**
- Storage version to `v0.2.0`
- New ZEI API
  - Combine anonymous spend/view keypair. (Breaking change to old data)
  - Tag (like signature) in anon_xfr to protect non-malleability in tx
  - Fee calculate at the platform.

### NOTICE
- `wasm` changes: assignees  @okovalov 
  - src/components/wasm/src/wasm_data_model.rs
    - add `AxfrOwnerMemo` for abar, bar still use `OwnerMemo`
    - update `AnonKeys`
       ```
       pub(crate) spend_key: String,
       pub(crate) pub_key: String,
       pub(crate) view_key: String,
       ```
  - src/components/wasm/src/wasm.rs
    - rename `AnonBlindAssetRecord` to `AnonAssetRecord`
    - delete param `enc_key: &XPublicKey,` in `add_operation_bar_to_abar`
    - update param  `owner_memo: AxfrOwnerMemo` in `add_operation_abar_to_bar` 
    - same in `add_operation_anon_transfer` (update params type)
    - same in `get_anon_balance`
    - same in `get_open_abar`
    - same in `gen_nullifier_hash`
    - same in `open_abar`
    - `AnonTransferOperationBuilder`
      - same in `add_input`
      - delete `dec_key: &XSecretKey,` in `add_input`
      - delete `to_enc_key: XPublicKey,` in `add_output`
      - delete `set_fra_remainder_receiver`, no need encrypt key from outside when build abar.
  - add `axfr_viewkey_from_string`

- `fn` changes:
  - delete `to-enc-key`  in `anon-transfer`
  - delete `decryption-key-file` and `to-enc-key-file` in `anon-transfer-batch`
  assignees: @tiannian
 
- `tx_builder` changes:
  - xx

### CHECKLIST
- [x] new storage
- [x] new ZEI API
- [x] fee calculate algorithm 
  - [x] old `50_0000 + 10_0000 * x + 20_0000 * y + (10_000 * extra_outputs)` in ledger)
  - ~~TBD new~~ 
- [x] tag and seralize tx body.
- [x] TM test CI

### CODE REVIEW

**Comment by findora-sun** [comment]
Before merge, need zei release new tag.

**Comment by findora-crypto** [comment]
It is surprising that this will pass this easily. Let me have a try.

**Comment by akhilpeddireddy** [comment]
Screen Shot 2022-07-04 at 12 21 12 AM

I ran the tests and still noticing this issue of 'missing abar' after bar->abar conversion

**Comment by akhilpeddireddy** [comment]
Probably because of the height. Let me check.

**Pull request merged**
