### PR TITLE
fix undelegation missing reward.

### PR DESCRIPTION
**Pull request by shaorongqiang**
* **make sure that you have executed all the following process and no errors occur**
  - [ ] make fmt
  - [ ] make lint
  - [ ] make test

* **The major changes of this PR**

* **The major impacts of this PR**
  - [ ] Impact WASM?
  - [ ] Impact Web3 API?
  - [ ] Impact mainnet data compatibility?

* **Extra documentations**
 修复的解质押的21天内产生的奖励diushi问题

### CODE REVIEW

**Comment by malefooo** [comment]
can you more detail for this?
upload a screenshot of the before and after modification?
@shaorongqiang

**Comment by shaorongqiang** [comment]
## 这是修改前的









## 这是修改后

**Comment by malefooo** [comment]
You should try loading historical data

**Comment by shaorongqiang** [comment]
Add a checkpoint.fix_undelegation_missing_reward_height,
When it is higher than this height, calim will be placed on the client's account address.
When this height is not reached, it is still calim to the proxy address,
In this way, there will be no inconsistencies in app_hash.

**Comment by shaorongqiang** [comment]
> You should try loading historical data

I added a checkpoint.fix_undelegation_missing_reward_height,
When it is higher than this height, calim will be placed on the client's account address.
When this height is not reached, it is still calim to the proxy address,
In this way, there will be no inconsistencies in app_hash.

**Review by tiannian — APPROVED** [review]

**Pull request merged**
