### PR TITLE
fix frc20 code

### LINKED ISSUE #146: 0x1000 precompile contract is not fully compatible with IERC20 in solidity.
Solidity will add an `extcodesize` check if the code is still there. 
So if I use [IERC20](https://github.com/Uniswap/v2-core/blob/master/contracts/interfaces/IERC20.sol) here to interact with our precompile contracts. It would failed.

>Screenshots:

Use the IERC20 token to implement a smart contract
>2、
Use the contract to interact with 0x1000
>3、
Transaction will revert by `iszero` after `extcodesize`

### PR DESCRIPTION
**Pull request by simonjiao**
* **make sure that you have executed all the following process and no errors occur**
  - [x] make fmt
  - [x] make lint
  - [x] make test

* **The major changes of this PR**
fix frc20 precompile address when query frc20 account code
close #146 

* **Extra documentations**

### CODE REVIEW

**Comment by simonjiao** [comment]
local tests passed
图片

**Comment by ws4charlie** [comment]
The way looks good and simple if it works for Ching-Hua.

**Review by ws4charlie — APPROVED** [review]
looks good

**Review by frostfrog — APPROVED** [review]
LGTM. remember this would be a hardfork change if any transaction already interacted via these instructions with this address.

**Pull request merged**
