### PR TITLE
FO-968: Increment Nonce for CheckTx run mode without executing EVM transaction PORT TO MAIN

### PR DESCRIPTION
**Pull request by kevinssgh**
https://github.com/FindoraNetwork/platform/commit/b0b98034a87b0e3ca762496a0614d2267e469bb8

### CODE REVIEW

**Review by ws4charlie — APPROVED** [review]
looks good

**Comment by tiannian** [comment]
This PR will merge later.

**Review by ws4charlie — APPROVED** [review]
The nonce fix looks good. `pre_execute()` does nothing now if we're delivering the transaction.

**Review by simonjiao — APPROVED** [review]
LGTM

**Pull request merged**
